apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthconnect-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthconnect-frontend
  template:
    metadata:
      labels:
        app: healthconnect-frontend
    spec:
      containers:
      - name: frontend
        image: healthconnect-frontend:latest # Ensure you build/tag this image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: healthconnect-frontend-service
spec:
  type: LoadBalancer # Exposes IP to access in browser
  selector:
    app: healthconnect-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80